engines:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
    
ratings:
  paths:
  - "**.java"
